version: '3.8'

services:
  account-service:
    build: ../account-entry
    container_name: account-service
    init: true
    ports:
      - "3001:3001"
    environment:
      - NODE_PORT=3001
      - DATABASE_PATH=./storage/database.sqlite
      - DB_LOGGING=false
      - CLASSIFIER_SERVICE_URL=http://classifier-service:3002
      - CLASSIFIER_SERVICE_ANALYSE_ENDPOINT=/analyze
    networks:
      - hackathon-net

  classifier-service:
    build: ../entry-rule-classifier
    container_name: classifier-service
    init: true
    ports:
      - "3002:3002"
    environment:
      - NODE_PORT=3002
      - DATABASE_PATH=./storage/database.sqlite
      - DB_LOGGING=false
      - ACCOUNT_ENTRIES_SERVICE_URL=http://account-service:3001
      - ACCOUNT_ENTRIES_ENDPOINT=/account-entries
      - BUDGET_SERVICE_URL=http://budget-service:3003
      - BUDGET_SERVICE_VERIFY_ENDPOINT=/budgets
    networks:
      - hackathon-net
    depends_on:
      - account-service
    
  budget-service:
    build: ../budget-service
    container_name: budget-service
    init: true
    ports:
      - "3003:3003"
    environment:
      - NODE_PORT=3003
      - DATABASE_PATH=./storage/database.sqlite
      - DB_LOGGING=false
      - ACCOUNT_ENTRIES_SERVICE_URL=http://account-service:3001
      - ACCOUNT_ENTRIES_ENDPOINT=/account-entries
      - CLASSIFIER_SERVICE_URL=http://classifier-service:3002
      - CLASSIFIER_SERVICE_ANALYSE_ENDPOINT=/rules
    networks:
      - hackathon-net
    depends_on:
      - classifier-service

networks:
  hackathon-net:
    driver: bridge